apiVersion: apps/v1
kind: Deployment
metadata:
  name: queries-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queries
  template:
    metadata:
      labels:
        app: queries
    spec:
      containers:
        - name: queries
          image: ahmedelsharkawy/queryservice:latest #get it from docker hub if the version is latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4002
