apiVersion: v1
kind: Pod
metadata:
  name: posts-pod
  labels:
    name: Posts
spec:
  containers:
    - name: posts-service
      image: ahmedelsharkawy/postservice:0.1
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 4000
